DROP TABLE `account`;--> statement-breakpoint
DROP TABLE `albums`;--> statement-breakpoint
DROP TABLE `albumsStats`;--> statement-breakpoint
DROP TABLE `albumsTypes`;--> statement-breakpoint
DROP TABLE `artists`;--> statement-breakpoint
DROP TABLE `artistsCredits`;--> statement-breakpoint
DROP TABLE `artistsCreditsName`;--> statement-breakpoint
DROP TABLE `artistsStats`;--> statement-breakpoint
DROP TABLE `artistsTypes`;--> statement-breakpoint
DROP TABLE `authenticator`;--> statement-breakpoint
DROP TABLE `countries`;--> statement-breakpoint
DROP TABLE `follows`;--> statement-breakpoint
DROP TABLE `genders`;--> statement-breakpoint
DROP TABLE `genres`;--> statement-breakpoint
DROP TABLE `genresToArtists`;--> statement-breakpoint
DROP TABLE `notificationRecipients`;--> statement-breakpoint
DROP TABLE `passwordResetTokens`;--> statement-breakpoint
DROP TABLE `playlistItems`;--> statement-breakpoint
DROP TABLE `playlists`;--> statement-breakpoint
DROP TABLE `reviewsAlbums`;--> statement-breakpoint
DROP TABLE `reviewsArtists`;--> statement-breakpoint
DROP TABLE `reviewsTracks`;--> statement-breakpoint
DROP TABLE `session`;--> statement-breakpoint
DROP TABLE `tracks`;--> statement-breakpoint
DROP TABLE `tracksStats`;--> statement-breakpoint
DROP TABLE `userNotifications`;--> statement-breakpoint
DROP TABLE `userProfiles`;--> statement-breakpoint
DROP TABLE `users`;--> statement-breakpoint
DROP TABLE `verificationTokens`;